@host = http://localhost:5555
@token = Bearer <copy your token here>

# ---------------------------------------------------------------------------------

### hitting the World Wide Web!
###
GET https://jsonplaceholder.typicode.com/todos/2

# ---------------------------------------------------------------------------------

### This is for an endpoint that would require JWT authorization
GET {{host}}/api/some-endpoint-with-auth
Authorization: {{token}}

# ---------------------------------------------------------------------------------
# Testing our own C# customers web service

###
GET {{host}}/api/customers

###
GET {{host}}/api/customers/1

###
POST {{host}}/api/customers
content-type: application/json

{
    "name": "Tomak Nowak",
    "tags": [ "Pierogi", "Bimber" ],
    "address": {
        "city": "Wroclaw",
        "country": "Poland"
    }
}

###
PUT {{host}}/api/customers/1/address
content-type: application/json

{
    "city": "Cracow",
    "country": "Poland"
}
